---
version: '3.4'
services:
  localstack:
    image: localstack/localstack
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
    ports:
      - 127.0.0.1:53:53
      - 127.0.0.1:53:53/udp
      - 127.0.0.1:443:443
      - 127.0.0.1:4510-4559:4510-4559
      - 127.0.0.1:4566:4566
    environment:
      DATA_DIR: /data
      DEBUG: 1
      DNS_ADDRESS: 127.0.0.1
      DOCKER_HOST: unix:///var/run/docker.sock
      LAMBDA_EXECUTOR: docker-reuse
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY:-}
